// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSyncStatus: () => typedError<SyncStatus, string>(__TAURI_INVOKE("get_sync_status")),
	getTodosByStatus: (status: TodoStatus) => typedError<TodoItem[], string>(__TAURI_INVOKE("get_todos_by_status", { status })),
	addTodo: (text: string) => typedError<TodoItem, string>(__TAURI_INVOKE("add_todo", { text })),
	updateTodoStatus: (id: string, status: TodoStatus) => typedError<null, string>(__TAURI_INVOKE("update_todo_status", { id, status })),
	deleteTodo: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_todo", { id })),
	manualReconnect: () => typedError<null, string>(__TAURI_INVOKE("manual_reconnect")),
};

/* Types */
export type SyncStatus = { status: "connecting" } | { status: "connected" } | { status: "disconnected" };

export type TodoItem = {
	id: string,
	text: string,
	status: TodoStatus,
};

export type TodoStatus = "todo" | "archived" | "completed";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

