// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	getTodos: () => __TAURI_INVOKE<TodoItem[]>("get_todos"),
};

/* Types */
export type TodoItem = {
	id: number,
	text: string,
	completed: boolean,
	inWorkingSet: boolean,
};

